version: "3.3"
services:
    wordpress:
        image: wordpress
        depends_on: 
          - mysql
        restart: always
        ports:
          - 8080:80
        environment:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_USER: kerri
          WORDPRESS_DB_PASSWORD: kerri
          WORDPRESS_DB_NAME: wordpress
        volumes:
          - wordpress:/var/www/html
        networks: 
            - frontend
            - backend
    web:
        build: './apache/'
        depends_on:
            - php
            - mysql
        ports: 
            - "8000:80"     
        networks: 
            - frontend
            - backend
        volumes:
            - ./Apache/public_html/:/var/www/html/
    php:
        build: './php/'
        networks: 
            - backend
    mysql:
        image: mysql:8.0.19
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: kerri
            MYSQL_PASSWORD: kerri
            MYSQL_ROOT_PASSWORD: kerri
        volumes:
            - mysql_db:/var/lib/mysql
        networks: 
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - mysql
        ports:
            - 8001:80
        environment:
            PMA_HOST: mysql
            PMA_USER: kerri
            PMA_PASSWORD: kerri
            PMA_PORT: 3306
            MYSQL_USER: kerri
            MYSQL_PASSWORD: kerri
            MYSQL_ROOT_PASSWORD: kerri

networks:
    frontend:
    backend:     
volumes:
    wordpress:
    mysql_db:
