version: "3.3"

networks:
    frontend:
    backend:     

volumes:
    wordpress:
    maria_db:

services:
    db:
        image: mariadb:10.5.2-bionic
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: kerri
            MYSQL_PASSWORD: kerri
            MYSQL_ROOT_PASSWORD: kerri
        volumes:
            - maria_db:/var/lib/mysql
        networks: 
            - backend
    adminer:
        image: adminer
        depends_on: 
            - db
        ports:
            - 8001:8080
        networks:
            - frontend
            - backend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - db
        ports:
            - 8002:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: kerri
        networks:
            - frontend
            - backend
    php:
        build: './php/'
        networks: 
            - backend
        volumes:
            - ./apache/public_html:/var/www/html/
    web:
        build: './apache/'
        depends_on:
            - php
            - db
        ports: 
            - "8000:80"
        networks: 
            - frontend
            - backend
        volumes:
            - ./apache/public_html/:/var/www/html/
    wordpress:
        image: wordpress
        restart: always
        depends_on:
          - db
        ports:
          - 8080:80
        environment:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_USER: kerri
          WORDPRESS_DB_PASSWORD: kerri
          WORDPRESS_DB_NAME: wordpress
        volumes:
          - wordpress:/var/www/html
        networks: 
            - frontend
            - backend    
